version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: todo

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
